### ISSUE TITLE
Ability to change the "docked" name

### ISSUE THREAD

**Issue by lucaspar** [user-none/KDocker#113]
If there are multiple docked apps they all share the "KDocker" name/identifier, which seems to prevent the user from setting independent visibility states (always shown / hidden) for these apps. Is there a way to specify this "KDocker" name on start? I couldn't find an option in `kdocker -h` to do that.

![kdocker](https://user-images.githubusercontent.com/7535699/167545589-46abccaf-08b3-4a6b-9036-5ab0ddc84a7f.png)

**Comment by user-none** [comment]
What is the app in this screenshot?

**Comment by lucaspar** [comment]
@user-none [Plasma system tray](https://userbase.kde.org/Plasma/SystemTray/en) with [candy icons](https://store.kde.org/p/1305251).

**Comment by user-none** [comment]
The Plasma system tray uses the application name of whatever created the icon in the tray. In this case it's KDocker because that's what created the icons. Unfortunately, there isn't anything that can be done to differentiate the name Plasma shows.

**Comment by lucaspar** [comment]
As I suspected, thanks for looking into it.

**Comment by Jieiku** [comment]
I was hoping kdocker had a way to name itself a certain way.

so for instance instead of typing

`kdocker thunderbird`

maybe something like:

`kdocker --name kdocker-thunderbid thunderbird`

and then kdocker name for that launch would be kdocker-thunderbird

I was thinking maybe I could change the name and compile a second version of the app, but having to do that everytime I need a unique name would be unfortunate.

I am wanting to do the exact same thing as the OP, always hide some things, always show other things.

**Comment by Jieiku** [comment]
Figured it out:

```bash
find /home/jieiku/.dev/KDocker -o -type f -print0 | xargs -0 sed -i 's/KDocker/Khide/g'

mv /home/jieiku/.dev/KDocker/resources/appstream/com.kdocker.KDocker.metainfo.xml.in /home/jieiku/.dev/KDocker/resources/appstream/com.kdocker.Khide.metainfo.xml.in

mv /home/jieiku/.dev/KDocker/resources/dbus/com.kdocker.KDocker.service.in /home/jieiku/.dev/KDocker/resources/dbus/com.kdocker.Khide.service.in

mv /home/jieiku/.dev/KDocker/resources/dbus/com.kdocker.KDocker.xml /home/jieiku/.dev/KDocker/resources/dbus/com.kdocker.Khide.xml
```

After you do that follow the build steps on the README page, then:

`sudo cp /home/jieiku/.dev/KDocker/build/kdocker /usr/bin/kdocker2`

Use the originally installed kdocker for things you want to show and use the newly renamed one for things you want to hide.
