### ISSUE TITLE
Option to close to tray

### ISSUE THREAD

**Issue by Massimo-B** [user-none/KDocker#127]
kdocker-5.4, Linux

Please add an option to make the application only hiding to tray when closing with Alt+F4. Currently the application and KDocker are terminating.

**Comment by Daxx** [comment]
https://github.com/user-none/KDocker/issues/15

**Comment by Misko-2083** [comment]
@user-none I've explored some options, and Xembed method seems right, with the container window but Xdnd protocol has to be figured out to make dnd to work. Apparently client messages between the windows have to be exchanged. But container window has to forward them. As for windows that are undecorated, setting decorations with motif_wm_hints seems like an option.

**Comment by user-none** [comment]
I attempted this and xembed did work however, forwarding messages for dnd was problematic. I attempted to forward messages but I couldn't get it working with Gnome. Also, any windows that turn off the window manager decorations and implement their own (Chrome) will not work because the close button is a regular button within the application window. So it cannot be intercepted. It's not great needing to tell people they need to reconfigure various apps to make them compatible (assuming those apps allow turning back on the window manager decorations instead of using their own).

**Comment by Misko-2083** [comment]
xdnd is tricky. https://github.com/PhilPotter/xlib_xdnd
As for the other windows maybe it can work with the helper window, a small button which is placed on top of the close button that follows the window. https://gist.github.com/Misko-2083/cf522cd238550a86383e7f966134eabb
![Peek 2024-08-20 22-58](https://github.com/user-attachments/assets/08f77398-5363-4161-a34c-dfe24e1eb24e)

**Comment by user-none** [comment]
I've looked at the overlay that follows the window. It looks strange for one thing. However, the bigger problem is getting the size and placement correct on windows that draw their own close button. Is it on the left, the right, what's the padding.

**Comment by Misko-2083** [comment]
Yes, I agree, there is no way to get padding,placement and size. The user would have to place it and set size, per window or globally. After that the window can be set to be transparent with Xshape.
But there would be other issues like keeping it on top of the window when the window stack changes. It would have to be on correct display, to close when the window minimizes/closes/sent_to_tray and probably more.

**Comment by Misko-2083** [comment]
Made some progress with the helper window method. It now follows the parent window without the delay.
Can be moved on Alt + Left_mouse drag, can be resized with Ctrl + Left_mouse drag
[gist code](https://gist.github.com/Misko-2083/9bf29803ffa0af42ceefae401a5c8152)  |  [video demo](https://gist.github.com/user-attachments/assets/38014f81-1986-4f30-a6d1-60c999f3bd68)
I guess the position and size can be saved somewhere and read when needed.

**Comment by Misko-2083** [comment]
The looks can be changed because the helper window is now drawn with Cairo.

I've been thinking about automatic positioning on windows, the only way is to get 1500+ images from variety of window managers and DEs Kde, xfce, openbox, etc. edit every one of those and mark where the close button is. Then train AI by feeding it all those images. Opncv is suitable for the job. So the idea is that kdocker gets the screenshot of the target window with the window borders and the AI figures out the position of the close button. It wouldn't be an easy task for sure and AI does make mistakes.

The easier solution: to do manual positioning and instead of AI let the user manually set positions, size  and perhaps colors/style for every app. Kdockew would have to manage all of those parameters.

Xembed is also an option for windows without CSD. Weeks ago I managed to get Xdnd working by passing it to the embedded window, although not tested on many apps. [gist code](https://gist.github.com/Misko-2083/650984ecb1edc754bd2e00c0abcd97b8)

**Comment by Misko-2083** [comment]
A lot of issues are now fixed:

- Limited helper window from moving outside the target window borders.
- Implemented anchoring at the edges so it keeps position when resizing target window
- Added a tooltip window and positions on the the screen
- Added button styles with rounded edges
[view code](https://gist.github.com/Misko-2083/9bf29803ffa0af42ceefae401a5c8152)

```
 gcc -o block_close block_close.c -lX11 -lcairo -lXrender -lXinerama 
./block_close 0x3e00003
```
![Image](https://github.com/user-attachments/assets/2268ce3b-3ed0-41b9-92bc-c83c7a8c8d61)

**Comment by Massimo-B** [comment]
Hi, thanks for all the contributions. But does this affect the initial request in some way?
 
> Please add an option to make the application only hiding to tray when closing with Alt+F4. Currently the application and KDocker are terminating.

**Comment by Misko-2083** [comment]
Yes with Xembed, by embedding a target window into into a container window a passing down XDnD for all windows can prevent closing them. This works because we can intercept closing events on a container window. This trick with helper windows is for windows with the client side decorations, to prevent clicking a button that closes the window. The solution would be combining the two methods.

There are probably more issues I haven't came across yet. It's still in the phase of exploring different solutions.
