### ISSUE TITLE
KDocker icons disappear when xfce4-panel restarts

### ISSUE THREAD

**Issue by birdie-github** [user-none/KDocker#48]
Steps to reproduce:

1. Login under XFCE
2. Run `kdocker thunderbird`
3. Run `xfce4-panel -r`

Result:
Thunderbird icon disappears completely and there's no way to get it back except exiting/killing Thunderbird and running it again.

**Comment by Daxx** [comment]
I would expect that because the connection between the desktop and kdocker is severed.
Another option is `pkill kdocker` (cancel kdocker process) which should make all docked apps in that session reappear. Then restart, of course.
Not a solution, just a fact of life ;)

**Comment by birdie-github** [comment]
Somehow other applications which have their own systray icons survive xfce4-panel restart.

Why?

**Comment by Daxx** [comment]
> Somehow other applications which have their own systray icons survive xfce4-panel restart. E.g. QuiteRSS is among them.
> 
> Why?

Because their own windows are managed the window manager (WM).
KDocker remembers the details of windows at the time of docking, then they are removed from WM control while docked and minimised (as I recall).
The WM can anticipate and repair the havoc caused by normal application windows but few, if any, WMs appreciate how KDocker works or the myriad disruptions from a multitude of WMs it has to try and cater for.

I'm trying to avoid asking the annoying questions: Why the need to restart the WM; is it to fix another problem? Can you find another solution, like making a script that restarts XFCE and KDocker together? (etc.)

IOW, if I had the same issue, I don't think I'd attempt to patch KDocker to fix it.
With eight apps docked, I'd have to guess the changed state of all the windows after someone pulled the carpet from under my feet with a WM restart. :)

**Comment by birdie-github** [comment]
I just wanted to make KDocker a little bit more fool-proof but you sound like it's a lot of work for almost nothing in which case I guess this bug report may be safely closed.

**Comment by qwertychouskie** [comment]
Also, FYI, if you're only using KDocker for TBird you can also use https://addons.thunderbird.net/en-US/thunderbird/addon/minimizetotray-reanimated/ or https://github.com/Ximi1970/FireTray/releases

Also, `xfce4-panel` is just the panel application, `xfwm4` is the window manager.

**Comment by Daxx** [comment]
> `xfce4-panel` is just the panel application, `xfwm4` is the window manager.

Thanks, I'm locked in to KDE & Plasma. On the rare occasion when part of the desktop (tray panel) reset itself, all my docked icons reappeared in a different order, which meant it was easier to rerun my startup script to get back to a familiar environment.

**Comment by Daxx** [comment]
> `xfce4-panel` is just the panel application, `xfwm4` is the window manager.

Thanks, the connection to the WM is what KDocker loses, so it amounts to the same thing.
I'm locked in to KDE & Plasma. On a rare occasion when part of the desktop (tray panel) reset itself, all my docked icons reappeared in a different order, which meant it was more convenient to rerun my startup script to restore a familiar environment.

**Comment by birdie-github** [comment]
@qwertychouskie 

This add-on uses native code which is a huge no-no for me.
