### ISSUE TITLE
Minimizing Thunderbird doesn't minimize to icon

### ISSUE THREAD

**Issue by Lastique** [user-none/KDocker#56]
I'd like to configure KDocker with Thunderbird so that it works as a normal "minimize to tray icon" would. Specifically:
- When the application is not minimized, it is present in the taskbar. Its icon may or may not be in the tray, that's not important.
- When I click Minimize, the application minimizes to the tray icon, disappearing from the taskbar.
- When I click on the tray icon, the application restores, reappearing in the taskbar.

It seems, KDocker doesn't work that way, at least I couldn't make it to:
- I start the application with the command line: `kdocker -m -q thunderbird %u`. The application starts maximized, present in the taskbar. KDocker creates an icon in the tray.
- I click Minimize button. The application minimizes to the taskbar (the application button on the taskbar stays present, greyed out as for usual minimized windows).
- I click on the application button in the taskbar. The application begins restore animation but then disappears. It gets removed from the taskbar and ends up minimized into the tray icon.
- I click on the tray icon. The application restores proper, reappearing in the taskbar.

I'm not sure if KDocker is supposed to be working as expected in my setup, or if there is a way to configure it that way. If there is, please advise. If not, please consider this a feature request. Either way, the fact that the application gets minimized to icon on restoring a minimized window doesn't look right.

Kubuntu 19.04, KDE Plasma 5.15.4, KDE Frameworks 5.56.0, Qt 5.12.2, KDocker 5.0.

**Comment by Daxx** [comment]
Thunderbird, with KDocker, should behave as you described. It does for me.

This seems strange, though:

> * I click on the application button in the taskbar. The application begins restore animation but then disappears. It gets removed from the taskbar and ends up minimized into the tray icon.

1) Please check in `~/.kde/share/config/kwinrulesrc` to see if there's an entry for thunderbird which might be interfering with its behaviour. Those settings are changed by right-clicking on the icon at the left of the thunderbird window title (App Icon?) -> More Actions -> Special Window Settings (or Special Application Settings).

2) Any difference when you start with `kdocker -m -q -t thunderbird %u` to skip taskbar?

**Comment by Lastique** [comment]
1. There was a rule for Thunderbird, which maximized the main window initially. I removed the rule but that didn't help, the behavior is the same. There is also an "All windows" rule, which I think is present by default. It only has "Block compositing: Force: No" effect. Disabling that option also doesn't help.

2. `-t` makes Thunderbird never appear in the taskbar, even when not minimized. Clicking on the tray icon minimizes and restores TB, as expected.

**Comment by FWDekker** [comment]
I have the exact same issue: I run KDocker as `kdocker -m thunderbird` and when I minimise it it just stays there greyed out, but when I click on it it starts the opening animation before quickly disappearing to the tray.

I've also made the following observations:
* Switching to another desktop while it's greyed out will move it to the tray after all.
* Pressing `Meta + 4` (if Thunderbird is the fourth application in my task manager) while Thunderbird is open will actually correctly move it to tray.

| Software | Version |
|---|---|
| Kubuntu | 18.04 |
| KDE Plasma | 5.12.9 |
| KDE Frameworks | 5.44.0 |
| Qt | 5.9.5 |
| KDocker | 5.0 |

**Comment by fabianski7** [comment]
I can confirm that this problem is still in the latest version of the kdocker.

Alternatively I'm using -q to skip the taskbar and the [Minimize on Close](https://addons.thunderbird.net/en-US/thunderbird/addon/minimize-on-close/?src=search) extension

**Comment by Daxx** [comment]
> I can confirm that this problem is still in the latest version of the kdocker.

Controversial comment ;)
If KDocker behaves as intended with most/all apps except TB, one might fairly suspect it's a problem in TB.  I use TB and have never noticed this **until just now** when I followed @Lastique steps but it doesn't happen every time.

This might not be a solution for you but I'll try to explain why it doesn't affect me ( including minimize on [X] close )
Using `kdocker -o -q thunderbird`
To look at TB (restore or bring into focus), click on its tray icon, or the window, if visible.
To hide TB,  click on its tray icon, or minimize.
I've never found a situation where clicking on the tray icon doesn't 'do the right thing' so the only reason to click on [X] would be to close TB, which I don't because it stays part of my KDE session for next startup. I usually "Undock All" before ShutDown because KDocker is not session-friendly.

> Alternatively I'm using -q to skip the taskbar and the [Minimize on Close](https://addons.thunderbird.net/en-US/thunderbird/addon/minimize-on-close/?src=search) extension

Interesting that the add-on author recommends using KDocker to move to tray. Maybe doesn't see this "problem".

There does seem to be a problem with the interaction between TB and KDocker but, bear in mind that TB once had "minimize to tray" but they removed the function because BillGatesWorld devs announced that Systray should only be used for notifications (?). Maybe it started to look too much like a Mac :D

Then [FireTray ... then no FireTray](https://github.com/firetray-updates/FireTray/tree/thunderbird-57)
