### ISSUE TITLE
Maximizing an application highlights the previously opened application in the taskbar.

### ISSUE THREAD

**Issue by Kj-is-escape** [user-none/KDocker#77]
In KDE when undocking a window if there is a window already open and maximized this previously maximized window gets highlighted (as if a pop up would have interrupted your work, to suggest that you should go back I think).   
This is normally not a problem but if the option of automatically hiding the taskbar is enabled this prevents it from hiding, and to properly see the undocked window it is necessary to go to the previous window and then to back to the undocked one.  
I would like to know if there is something that can be done to prevent this from happening.

**Comment by Daxx** [comment]
> ... this previously maximized window gets highlighted ...

I assume you mean that it's shown as the active task on the taskbar, rather than the undocked window that you expect?

Sounds like window manager (WM) preference.

I tried to reproduce your problem as I understand it and it seemed okay (which probably means I misunderstood your problem or my setting are different). This was made more difficult because I try to undock an application by right-clicking on the tray icon which shows the KDocker context menu but as soon as I move up the choices, the WM detects that I've moved off the taskbar, so it hides it **and** hides the context menu that I want to use. Can get round round that by using the cursor keys to choose but it demonstrates the quirkiness of WM's.

An example for me is when I "Undock All", the last one to undock becomes active on the taskbar. Clicking on that task doesn't minimise it, as I'd like, it does absolutely nothing until I click on any other task on the taskbar, first.

**Comment by Kj-is-escape** [comment]
Sorry, I got the terms wrong, when I said "undock" I meant maximize (or show), when I maximize the docked window. To reproduce the problem you can right-click the tray icon and select show application from the menu while another window is opened.

**Comment by Daxx** [comment]
> Sorry, I got the terms wrong, when I said "undock" I meant maximize (or show), when I maximize the docked window. To reproduce the problem you can right-click the tray icon and select show application from the menu while another window is opened.

With taskbar set to auto-hide. Firefox full screen. Editor hidden. Both docked.
Right-click the editor's tray icon and select show application from the menu ...
Editor window appears. Move cursor off taskbar, taskbar auto-hides.
Can't see your problem, sorry.

**Comment by Kj-is-escape** [comment]
I tried it with other programs and you're right, it's a problem with Spotify for linux. I don't understand why it happens but it's definitely not kdocker's fault.
