### ISSUE TITLE
Is it possible to get KDock-ed application icons into 'Show Hidden Icons' menu?

### ISSUE THREAD

**Issue by RonCam** [user-none/KDocker#9]
KDocker has functioned correctly, to put icons for 1)system-wide equalizer and 2)PulseAudio volume control -- into the System Tray.  I can move them around, in this area, but only within limits.

When I try to drag these icons into the Hidden Icons menu, they just 'pop back' to their original location.  

My objective was to gain some space in both the System Tray and Task Manager areas.  They are now 'out' of the former, but occupying the same horizontal space, as before.  

Is it possible, in any version of KDocker, to have the newly created System Tray Icons moved into the Hidden area?
Thanks!

KDocker 4.6 (from Linux Mint repo)
Linux Mint Quiana / KDE Platform Version 4.13.3

**Comment by Daxx** [comment]
Those sounds like apps which should have their own System Tray support (e.g. KMix has).  If you use KDocker with them, that support will be defeated because all KDocker items have the same name in "System Tray Settings -> Entries" (seen by right-clicking in the System Tray area).  In other words, there's no code in any KDocker that I know about to support what you're looking for but you should be able to do it by other means.

**Comment by RonCam** [comment]
Thanks for telling me it should be there, and where to look for it.  This time, I just kept on looking until I found it.  

For anyone else who comes across this post in a search, it's at:
Icon Settings -> Application -> Advanced Options -> Startup -> [  ] Place in System Tray

Let me first reset both applications to be 'out of' the System Tray, reboot, then bring them back in with their own settings, to avoid creating a conflict with KDocker.  Again, thanks for teaching me about KDE -- I don't think there was a problem with KDocker, at all.
